---
title: "Cohort_77_WGCNA_analysis_MakeTOM"
author: "Nick Kron"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--Pick soft threshold function-->
```{r}

plotSoftThreshold <- function(datExpr){
  powers = c(c(1:10), seq(from = 12, to=20, by=2))
  # Call the network topology analysis function
  sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 5, networkType = "signed")
  # Plot the results:
  sizeGrWindow(9, 5)
  par(mfrow = c(1,2));
  cex1 = 0.9;
  # Scale-free topology fit index as a function of the soft-thresholding power
  plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
       xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
       main = paste("Scale independence"));
  text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
       labels=powers,cex=cex1,col="red");
  # this line corresponds to using an R^2 cut-off of h
  abline(h=0.90,col="red", lty = 1)
  abline(h=0.80,col="red", lty = 2)
  # Mean connectivity as a function of the soft-thresholding power
  plot(sft$fitIndices[,1], sft$fitIndices[,5],
       xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
       main = paste("Mean connectivity"))
  text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
}

```

<!-- Set up env --->
```{r}

# Load the WGCNA package
library(WGCNA)
# The following setting is important, do not omit.
options(stringsAsFactors = FALSE)

```

#get TOM for All
```{r}
lnames = load(file = "../data/r_data/All_dataInput.R")
lnames

plotSoftThreshold(datExpr)
```

###Adjacencies
```{r}

softPower = 12  
adjacency = adjacency(datExpr, power = softPower, type = "signed", corFnc = "bicor", corOptions = list(maxPOutliers = 0.1))
```

##TOM
```{r}

TOM = TOMsimilarity(adjacency, TOMType = "signed")
save(TOM, softPower, file = "../data/r_data/All_TOM.R")

```

##Clear the data
```{r}
rm(softPower, adjacency, TOM, datExpr, datTraits)
```

#get TOM for BSC
```{r}
lnames = load(file = "../data/r_data/BSC_dataInput.R")
lnames

plotSoftThreshold(datExpr_bsc)
```

###Adjacencies
```{r}

softPower = 16  
adjacency = adjacency(datExpr_bsc, power = softPower, type = "signed", corFnc = "bicor", corOptions = list(maxPOutliers = 0.1))
```

##TOM
```{r}

TOM = TOMsimilarity(adjacency, TOMType = "signed")
save(TOM, softPower, file = "../data/r_data/BSC_TOM.R")

```

##Plot TOM
```{r, fig.width= 6, fig.height=6, eval = FALSE}
#lnames = load(file = "BSC_TOM.R")
#lnames

dissTOM = 1 - TOM
nGenes = nrow(TOM)

nSelect = 500
# For reproducibility, we set the random seed
set.seed(10)
select = sample(nGenes, size = nSelect)
selectTOM = dissTOM[select, select]
# There's no simple way of restricting a clustering tree to a subset of genes, so we must re-cluster.
selectTree = hclust(as.dist(selectTOM), method = "average")
#selectColors = moduleColors[select]
# Open a graphical window
#sizeGrWindow(9,9)
# Taking the dissimilarity to a power, say 10, makes the plot more informative by effectively changing
# the color palette; setting the diagonal to NA also improves the clarity of the plot
plotDiss = selectTOM^7
diag(plotDiss) = NA
pdf(file = "../figures/Cohort_77_BSC_TOM_Heatmap.pdf")
TOMplot(plotDiss, selectTree, main = "Network heatmap plot, selected genes", terrainColors = FALSE)
dev.off()


```


##Clear the data
```{r}
rm(softPower, adjacency, TOM, datExpr_bsc, datTraits_bsc, dissTOM, plotDiss, selectTOM, selectTree)
```

#get TOM for PVC
```{r}
lnames = load(file = "../data/r_data/PVC_dataInput.R")
lnames

#plotSoftThreshold(datExpr_pvc)
```

###Adjacencies
```{r}

softPower = 16  
adjacency = adjacency(datExpr_pvc, power = softPower, type = "signed", corFnc = "bicor", corOptions = list(maxPOutliers = 0.1))
```

##TOM
```{r}

TOM = TOMsimilarity(adjacency, TOMType = "signed")
save(TOM, softPower, file = "../data/r_data/PVC_TOM.R")

```

##Plot TOM
```{r, fig.width= 6, fig.height=6, eval = FALSE}
#lnames = load(file = "../data/r_data/PVC_TOM.R")
#lnames

dissTOM = 1 - TOM
nGenes = nrow(TOM)

nSelect = 500
# For reproducibility, we set the random seed
set.seed(10)
select = sample(nGenes, size = nSelect)
selectTOM = dissTOM[select, select]
# There's no simple way of restricting a clustering tree to a subset of genes, so we must re-cluster.
selectTree = hclust(as.dist(selectTOM), method = "average")
#selectColors = moduleColors[select]
# Open a graphical window
#sizeGrWindow(9,9)
# Taking the dissimilarity to a power, say 10, makes the plot more informative by effectively changing
# the color palette; setting the diagonal to NA also improves the clarity of the plot
plotDiss = selectTOM^7
diag(plotDiss) = NA
pdf(file = "../figures/Cohort_77_PVC_TOM_Heatmap.pdf")
TOMplot(plotDiss, selectTree, main = "Network heatmap plot, selected genes", terrainColors = FALSE)
dev.off()

```

##Clear the data
```{r}
rm(softPower, adjacency, TOM, datExpr_pvc, datTraits_pvc,dissTOM, plotDiss, selectTOM, selectTree)
```

#Plot superimposed PVC and BSC soft thresholds
```{r}

load("../data/r_data/Consensus_dataInput.R")
nSets = 2

# Choose a set of soft-thresholding powers
powers = c(seq(4, 10, by = 1), seq(12, 20, by = 2))
# Initialize a list to hold the results of scale-free analysis
powerTables = vector(mode = "list", length = nSets)
# Call the network topology analysis function for each set in turn
for (set in 1:nSets)
  powerTables[[set]] = list(data = pickSoftThreshold(multiExpr[[set]]$data, powerVector = powers, verbose = 2)[[2]])
collectGarbage()
#Plot the results:
colors = c("black", "red")
# Will plot these columns of the returned scale free analysis tables
plotCols = c(2, 5, 6, 7)
colNames = c(
  "Scale Free Topology Model Fit",
  "Mean connectivity",
  "Median connectivity",
  "Max connectivity"
)
# Get the minima and maxima of the plotted points
ylim = matrix(NA, nrow = 2, ncol = 4)
for (set in 1:nSets) {
  for (col in 1:length(plotCols)) {
    ylim[1, col] = min(ylim[1, col], powerTables[[set]]$data[, plotCols[col]], na.rm = TRUE)
    ylim[2, col] = max(ylim[2, col], powerTables[[set]]$data[, plotCols[col]], na.rm = TRUE)
  }
}
#Plot the quantities in the chosen columns vs. the soft thresholding power
pdf(file = "../figures/ScaleFreeTopology_Connectivity_both.pdf", width = 7, height = 7)
sizeGrWindow(7, 7)
par(mfcol = c(2, 2))
par(mar = c(4.2, 4.2 , 2.2, 0.5))
cex1 = 0.7
for (col in 1:length(plotCols))
  for (set in 1:nSets) {
    if (set == 1) {
      plot(
        powerTables[[set]]$data[, 1],-sign(powerTables[[set]]$data[, 3]) * powerTables[[set]]$data[, 2],
        xlab = "Soft Threshold (power)",
        ylab = colNames[col],
        type = "n",
        ylim = ylim[, col],
        main = colNames[col]
      )
      addGrid()

    }
    
    if (col == 1) {
      text(
        powerTables[[set]]$data[, 1],-sign(powerTables[[set]]$data[, 3]) * powerTables[[set]]$data[, 2],
        labels = powers,
        cex = cex1,
        col = colors[set]
      )
    } else
      text(
      powerTables[[set]]$data[, 1],
      powerTables[[set]]$data[, plotCols[col]],
      labels = powers,
      cex = cex1,
      col = colors[set]
    )
    if (col == 1) {
      legend("bottomright",
             legend = setLabels,
             col = colors,
             pch = 20)
    } else
      legend("topright",
                 legend = setLabels,
                 col = colors,
                 pch = 20)
  }
dev.off()


```

